defaults:
  - _self_
  - agent: potil
  - suite: robotgym
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/path/to/dir/ROT'

nstep: 3
# misc
seed: 2
device: cuda
save_video: true
# save_train_video: false
use_tb: true

# experiment
obs_type: 'pixels'
experiment: eval_${suite.name}_${task_name}_seed_${seed}

# Number of evaluation trajectories
num_eval: 20

# Start points path
eval_starts: '${root_dir}/ROT/eval_starts/${suite.name}_${obs_type}/${task_name}'

# Load weights
weight: '${root_dir}/ROT/weights/${suite.name}_${obs_type}/${task_name}/bc.pt'

# Train with BC loss
bc_regularize: true
bc_weight_type: 'qfilter' # linear, qfilter

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm


